### ISSUE TITLE
error 500 on request /api/comfy

### ISSUE THREAD

**Issue by veka-server** [ViewComfy/ViewComfy#32]
**Description**: When attempting to execute a workflow by clicking the "Generate" button, the nodejs console error is thrown, preventing the workflow from running as expected. The error appears to be related to a fetch failed issue in Node.js, with a ConnectTimeoutError. Additionally, there’s a warning regarding missing unique keys in React components.

Error Details
The full error log is as follows:

```
Failed to run the workflow
{
  error: TypeError: fetch failed
      at node:internal/deps/undici/undici:13392:13
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async ComfyUIAPIService.queuePrompt (webpack-internal:///(rsc)/./app/services/comfyui-api-service.ts:115:30)
      at async ComfyUIService.runWorkflow (webpack-internal:///(rsc)/./app/services/comfyui-service.ts:37:32)
      at async POST (webpack-internal:///(rsc)/./app/api/comfy/route.ts:34:24)
      at async /app/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:55755
      at async eO.execute (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:46523)
      at async eO.handle (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:57089)
      at async doRender (/app/node_modules/next/dist/server/base-server.js:1359:42)
      at async cacheEntry.responseCache.get.routeKind (/app/node_modules/next/dist/server/base-server.js:1581:28)
      at async DevServer.renderToResponseWithComponentsImpl (/app/node_modules/next/dist/server/base-server.js:1489:28)
      at async DevServer.renderPageComponent (/app/node_modules/next/dist/server/base-server.js:1920:24)
      at async DevServer.renderToResponseImpl (/app/node_modules/next/dist/server/base-server.js:1958:32)
      at async DevServer.pipeImpl (/app/node_modules/next/dist/server/base-server.js:917:25)
      at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/next/dist/server/next-server.js:272:17)
      at async DevServer.handleRequestImpl (/app/node_modules/next/dist/server/base-server.js:813:17)
      at async /app/node_modules/next/dist/server/dev/next-dev-server.js:339:20
      at async Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:154:20)
      at async DevServer.handleRequest (/app/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
      at async invokeRender (/app/node_modules/next/dist/server/lib/router-server.js:173:21)
      at async handleRequest (/app/node_modules/next/dist/server/lib/router-server.js:350:24)
      at async requestHandlerImpl (/app/node_modules/next/dist/server/lib/router-server.js:374:13)
      at async Server.requestListener (/app/node_modules/next/dist/server/lib/start-server.js:141:13) {
    [cause]: ConnectTimeoutError: Connect Timeout Error (attempted address: 172.21.0.4:8188, timeout: 10000ms)
        at onConnectTimeout (node:internal/deps/undici/undici:2599:28)
        at Immediate._onImmediate (node:internal/deps/undici/undici:2583:11)
        at process.processImmediate (node:internal/timers:511:21)
        at process.callbackTrampoline (node:internal/async_hooks:130:17) {
      code: 'UND_ERR_CONNECT_TIMEOUT'
    }
  }
}
Error parsing JSON. The extracted string might not be valid JSON. TypeError: nodeError.errors is not iterable
    at ComfyErrorHandler.extractErrors (webpack-internal:///(rsc)/./app/helpers/comfy-error-handler.ts:30:43)
    at ComfyErrorHandler.tryToParseWorkflowError (webpack-internal:///(rsc)/./app/helpers/comfy-error-handler.ts:19:30)
    at ComfyUIService.runWorkflow (webpack-internal:///(rsc)/./app/services/comfyui-service.ts:89:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async POST (webpack-internal:///(rsc)/./app/api/comfy/route.ts:34:24)
    at async /app/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:55755
    at async eO.execute (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:46523)
    at async eO.handle (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:57089)
    at async doRender (/app/node_modules/next/dist/server/base-server.js:1359:42)
    at async cacheEntry.responseCache.get.routeKind (/app/node_modules/next/dist/server/base-server.js:1581:28)
    at async DevServer.renderToResponseWithComponentsImpl (/app/node_modules/next/dist/server/base-server.js:1489:28)
    at async DevServer.renderPageComponent (/app/node_modules/next/dist/server/base-server.js:1920:24)
    at async DevServer.renderToResponseImpl (/app/node_modules/next/dist/server/base-server.js:1958:32)
    at async DevServer.pipeImpl (/app/node_modules/next/dist/server/base-server.js:917:25)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/next/dist/server/next-server.js:272:17)
    at async DevServer.handleRequestImpl (/app/node_modules/next/dist/server/base-server.js:813:17)
    at async /app/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/app/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/app/node_modules/next/dist/server/lib/router-server.js:173:21)
    at async handleRequest (/app/node_modules/next/dist/server/lib/router-server.js:350:24)
    at async requestHandlerImpl (/app/node_modules/next/dist/server/lib/router-server.js:374:13)
    at async Server.requestListener (/app/node_modules/next/dist/server/lib/start-server.js:141:13)
 POST /api/comfy 500 in 10526ms
 GET /api/comfy 405 in 20ms
```
Additionally, the browser console also shows the following warnings:

```
 500 Internal Server Error on POST http://192.168.1.132:3000/api/comfy
```

request return :
```
{
    "errorMsg": "Error running workflow",
    "errorDetails": [
        "Something went wrong running the workflow, the most common cases are missing nodes and running out of Vram. Make sure that you can run this workflow in your local comfy"
    ],
    "errorType": "ComfyWorkflowError"
}
```

the code /hooks/playground/use-post-playground.tsx :  
```
            formData.append("workflow", JSON.stringify(workflow));
            const response = await fetch(url, {
                method: "POST",
                body: formData
            });
```

**Comment by veka-server** [comment]
Apologies, I found the issue. It was a misconfiguration with my Docker network.
