### ISSUE TITLE
Error in Playground

### ISSUE THREAD

**Issue by achianes** [ViewComfy/ViewComfy#51]
> viewcomfy@0.1.0 dev
> cross-env NODE_OPTIONS='--inspect' next dev

Debugger listening on ws://127.0.0.1:9229/772a58c6-d53a-449d-af1b-9b5a80af243c
For help, see: https://nodejs.org/en/docs/inspector
Debugger listening on ws://127.0.0.1:9230/1065d1d7-c7b1-4dd9-9763-4e95aa897341
For help, see: https://nodejs.org/en/docs/inspector
   the --inspect option was detected, the Next.js router server should be inspected at port 9230.
  ▲ Next.js 14.2.11
  - Local:        http://localhost:3000
  - Environments: .env

 ✓ Starting...
 ✓ Ready in 1948ms
 ○ Compiling /api/comfy ...
 ✓ Compiled /api/comfy in 513ms (67 modules)
 ⨯ ReferenceError: File is not defined
    at POST (webpack-internal:///(rsc)/./app/api/comfy/route.ts:24:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/user/ComfyUI/ViewComfy/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:55755
    at async eO.execute (/home/user/ComfyUI/ViewComfy/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:46523)
    at async eO.handle (/home/user/ComfyUI/ViewComfy/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:57089)
    at async doRender (/home/user/ComfyUI/ViewComfy/node_modules/next/dist/server/base-server.js:1359:42)
    at async cacheEntry.responseCache.get.routeKind (/home/user/ComfyUI/ViewComfy/node_modules/next/dist/server/base-server.js:1581:28)
    at async DevServer.renderToResponseWithComponentsImpl (/home/user/ComfyUI/ViewComfy/node_modules/next/dist/server/base-server.js:1489:28)
    at async DevServer.renderPageComponent (/home/user/ComfyUI/ViewComfy/node_modules/next/dist/server/base-server.js:1920:24)
    at async DevServer.renderToResponseImpl (/home/user/ComfyUI/ViewComfy/node_modules/next/dist/server/base-server.js:1958:32)
    at async DevServer.pipeImpl (/home/user/ComfyUI/ViewComfy/node_modules/next/dist/server/base-server.js:917:25)
    at async NextNodeServer.handleCatchallRenderRequest (/home/user/ComfyUI/ViewComfy/node_modules/next/dist/server/next-server.js:272:17)
    at async DevServer.handleRequestImpl (/home/user/ComfyUI/ViewComfy/node_modules/next/dist/server/base-server.js:813:17)
    at async /home/user/ComfyUI/ViewComfy/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/home/user/ComfyUI/ViewComfy/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/home/user/ComfyUI/ViewComfy/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/home/user/ComfyUI/ViewComfy/node_modules/next/dist/server/lib/router-server.js:173:21)
    at async handleRequest (/home/user/ComfyUI/ViewComfy/node_modules/next/dist/server/lib/router-server.js:350:24)
    at async requestHandlerImpl (/home/user/ComfyUI/ViewComfy/node_modules/next/dist/server/lib/router-server.js:374:13)
    at async Server.requestListener (/home/user/ComfyUI/ViewComfy/node_modules/next/dist/server/lib/start-server.js:141:13)
 POST /api/comfy 500 in 712ms

**Comment by chinchaun** [comment]
hey @achianes, I think the main issue is around NextJS, try updating Node to v20, you can check it here

https://github.com/vercel/next.js/discussions/56032

**Comment by chinchaun** [comment]
this should be fixed
