### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by laixiao** [ViewComfy/ViewComfy#55]
=======Comfyui error=======
To see the GUI go to: http://0.0.0.0:8188
To see the GUI go to: http://[::]:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
Error handling request
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 378, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp\\_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01\x01j\x01'
      ^
Error handling request
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 378, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp\\_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01\x01y\x01'
===================

=======ViewComfy Error：===========
Failed to run the workflow
{
  error: TypeError: fetch failed
      at node:internal/deps/undici/undici:13185:13
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async ComfyUIAPIService.queuePrompt (webpack-internal:///(rsc)/./app/services/comfyui-api-service.ts:114:30)
      at async ComfyUIService.runWorkflow (webpack-internal:///(rsc)/./app/services/comfyui-service.ts:37:32)
      at async POST (webpack-internal:///(rsc)/./app/api/comfy/route.ts:39:24)
      at async C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:55755
      at async eO.execute (C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:46523)
      at async eO.handle (C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:57089)
      at async doRender (C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\server\base-server.js:1359:42)
      at async cacheEntry.responseCache.get.routeKind (C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\server\base-server.js:1581:28)
      at async DevServer.renderToResponseWithComponentsImpl (C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\server\base-server.js:1489:28)
      at async DevServer.renderPageComponent (C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\server\base-server.js:1920:24)
      at async DevServer.renderToResponseImpl (C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\server\base-server.js:1958:32)
      at async DevServer.pipeImpl (C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\server\base-server.js:917:25)
      at async NextNodeServer.handleCatchallRenderRequest (C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\server\next-server.js:272:17)
      at async DevServer.handleRequestImpl (C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\server\base-server.js:813:17)
      at async C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\server\dev\next-dev-server.js:339:20
      at async Span.traceAsyncFn (C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\trace\trace.js:154:20)
      at async DevServer.handleRequest (C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
      at async invokeRender (C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\server\lib\router-server.js:173:21)
      at async handleRequest (C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\server\lib\router-server.js:350:24)
      at async requestHandlerImpl (C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\server\lib\router-server.js:374:13)
      at async Server.requestListener (C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\server\lib\start-server.js:141:13) {
    [cause]: [Error: C86B0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:355:
    ] {
      library: 'SSL routines',
      reason: 'wrong version number',
      code: 'ERR_SSL_WRONG_VERSION_NUMBER'
    }
  }
}
Error parsing JSON. The extracted string might not be valid JSON. TypeError: nodeError.errors is not iterable
    at ComfyErrorHandler.extractErrors (webpack-internal:///(rsc)/./app/helpers/comfy-error-handler.ts:30:43)
    at ComfyErrorHandler.tryToParseWorkflowError (webpack-internal:///(rsc)/./app/helpers/comfy-error-handler.ts:19:30)
    at ComfyUIService.runWorkflow (webpack-internal:///(rsc)/./app/services/comfyui-service.ts:89:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async POST (webpack-internal:///(rsc)/./app/api/comfy/route.ts:39:24)
    at async C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:55755
    at async eO.execute (C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:46523)
    at async eO.handle (C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:57089)
    at async doRender (C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\server\base-server.js:1359:42)
    at async cacheEntry.responseCache.get.routeKind (C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\server\base-server.js:1581:28)
    at async DevServer.renderToResponseWithComponentsImpl (C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\server\base-server.js:1489:28)
    at async DevServer.renderPageComponent (C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\server\base-server.js:1920:24)
    at async DevServer.renderToResponseImpl (C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\server\base-server.js:1958:32)
    at async DevServer.pipeImpl (C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\server\base-server.js:917:25)
    at async NextNodeServer.handleCatchallRenderRequest (C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\server\next-server.js:272:17)
    at async DevServer.handleRequestImpl (C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\server\base-server.js:813:17)
    at async C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\trace\trace.js:154:20)
    at async DevServer.handleRequest (C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
    at async invokeRender (C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\server\lib\router-server.js:173:21)
    at async handleRequest (C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\server\lib\router-server.js:350:24)
    at async requestHandlerImpl (C:\Users\Administrator\Desktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\server\lib\router-server.js:374:13)
    at async Server.requestListener (C:\Users\Administrator\D
[view_comfy.json](https://github.com/user-attachments/files/18034759/view_comfy.json)
esktop\ai\HunyuanVideo\python_embeded\ViewComfy\node_modules\next\dist\server\lib\start-server.js:141:13)
 POST /api/comfy 500 in 234ms

=======my view_comfy.json=========
[view_comfy.json](https://github.com/user-attachments/files/18034761/view_comfy.json)

**Comment by laixiao** [comment]
============console===========


Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
app-index.tsx:25  Warning: Extra attributes from the server: inject_video_svd
    at body
    at html
    at RootLayout (Server)
    at RedirectErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/redirect-boundary.js:74:9)
    at RedirectBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/redirect-boundary.js:82:11)
    at NotFoundErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/not-found-boundary.js:76:9)
    at NotFoundBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/not-found-boundary.js:84:11)
    at DevRootNotFoundBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/dev-root-not-found-boundary.js:33:11)
    at ReactDevOverlay (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/react-dev-overlay/app/ReactDevOverlay.js:87:9)
    at HotReload (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/react-dev-overlay/app/hot-reloader-client.js:321:11)
    at Router (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/app-router.js:207:11)
    at ErrorBoundaryHandler (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/error-boundary.js:113:9)
    at ErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/error-boundary.js:160:11)
    at AppRouter (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/app-router.js:585:13)
    at ServerRoot (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/app-index.js:112:27)
    at Root (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/app-index.js:117:11)
window.console.error @ app-index.tsx:25
use-post-playground.tsx:31 
        
        
        POST http://localhost:3000/api/comfy 500 (Internal Server Error)
eval @ use-post-playground.tsx:31
onSubmit @ playground-page.tsx:105
eval @ index.esm.mjs:2271
await in eval
callCallback @ react-dom.development.js:20565
invokeGuardedCallbackImpl @ react-dom.development.js:20614
invokeGuardedCallback @ react-dom.development.js:20689
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:20703
executeDispatch @ react-dom.development.js:32128
processDispatchQueueItemsInOrder @ react-dom.development.js:32160
processDispatchQueue @ react-dom.development.js:32173
dispatchEventsForPlugins @ react-dom.development.js:32184
eval @ react-dom.development.js:32374
batchedUpdates$1 @ react-dom.development.js:24953
batchedUpdates @ react-dom.development.js:28844
dispatchEventForPluginEventSystem @ react-dom.development.js:32373
dispatchEvent @ react-dom.development.js:30141
dispatchDiscreteEvent @ react-dom.development.js:30112
app-index.tsx:25  Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <Fragment>. See https://reactjs.org/link/warning-keys for more information.
window.console.error @ app-index.tsx:25
console.error @ hydration-error-info.ts:72
printWarning @ react-jsx-dev-runtime.development.js:90
error @ react-jsx-dev-runtime.development.js:64
validateExplicitKey @ react-jsx-dev-runtime.development.js:1189
validateChildKeys @ react-jsx-dev-runtime.development.js:1110
jsxDEV$1 @ react-jsx-dev-runtime.development.js:967
onError @ playground-page.tsx:113
eval @ use-post-playground.tsx:74
await in eval
onSubmit @ playground-page.tsx:105
eval @ index.esm.mjs:2271
await in eval
callCallback @ react-dom.development.js:20565
invokeGuardedCallbackImpl @ react-dom.development.js:20614
invokeGuardedCallback @ react-dom.development.js:20689
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:20703
executeDispatch @ react-dom.development.js:32128
processDispatchQueueItemsInOrder @ react-dom.development.js:32160
processDispatchQueue @ react-dom.development.js:32173
dispatchEventsForPlugins @ react-dom.development.js:32184
eval @ react-dom.development.js:32374
batchedUpdates$1 @ react-dom.development.js:24953
batchedUpdates @ react-dom.development.js:28844
dispatchEventForPluginEventSystem @ react-dom.development.js:32373
dispatchEvent @ react-dom.development.js:30141
dispatchDiscreteEvent @ react-dom.development.js:30112
app-index.tsx:25  Warning: In HTML, <p> cannot be a descendant of <p>.
This will cause a hydration error.
    at p
    at p
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/@radix-ui/react-primitive/dist/index.mjs:36:13)
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/@radix-ui/react-dialog/dist/index.mjs:384:13)
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/@radix-ui/react-alert-dialog/dist/index.mjs:199:13)
    at _c7 (webpack-internal:///(app-pages-browser)/./components/ui/alert-dialog.tsx:111:11)
    at div
    at AlertDialogHeader (webpack-internal:///(app-pages-browser)/./components/ui/alert-dialog.tsx:71:11)
    at Slottable (webpack-internal:///(app-pages-browser)/./node_modules/@radix-ui/react-slot/dist/index.mjs:46:20)
    at div
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/@radix-ui/react-primitive/dist/index.mjs:36:13)
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/@radix-ui/react-dialog/node_modules/@radix-ui/react-dismissable-layer/dist/index.mjs:37:13)
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/@radix-ui/react-slot/dist/index.mjs:34:11)
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/@radix-ui/react-slot/dist/index.mjs:15:11)
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/@radix-ui/react-primitive/dist/index.mjs:36:13)
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/@radix-ui/react-focus-scope/dist/index.mjs:27:13)
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/@radix-ui/react-dialog/dist/index.mjs:315:13)
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/@radix-ui/react-dialog/dist/index.mjs:237:58)
    at Presence (webpack-internal:///(app-pages-browser)/./node_modules/@radix-ui/react-dialog/node_modules/@radix-ui/react-presence/dist/index.mjs:26:13)
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/@radix-ui/react-dialog/dist/index.mjs:209:64)
    at Provider (webpack-internal:///(app-pages-browser)/./node_modules/@radix-ui/react-alert-dialog/node_modules/@radix-ui/react-context/dist/index.mjs:34:15)
    at Provider (webpack-internal:///(app-pages-browser)/./node_modules/@radix-ui/react-dialog/node_modules/@radix-ui/react-context/dist/index.mjs:14:13)
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/@radix-ui/react-alert-dialog/dist/index.mjs:125:13)
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/@radix-ui/react-slot/dist/index.mjs:34:11)
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/@radix-ui/react-slot/dist/index.mjs:15:11)
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/@radix-ui/react-primitive/dist/index.mjs:36:13)
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/@radix-ui/react-dialog/node_modules/@radix-ui/react-portal/dist/index.mjs:22:24)
    at Presence (webpack-internal:///(app-pages-browser)/./node_modules/@radix-ui/react-dialog/node_modules/@radix-ui/react-presence/dist/index.mjs:26:13)
    at Provider (webpack-internal:///(app-pages-browser)/./node_modules/@radix-ui/react-dialog/node_modules/@radix-ui/react-context/dist/index.mjs:34:15)
    at DialogPortal (webpack-internal:///(app-pages-browser)/./node_modules/@radix-ui/react-dialog/dist/index.mjs:130:13)
    at AlertDialogPortal (webpack-internal:///(app-pages-browser)/./node_modules/@radix-ui/react-alert-dialog/dist/index.mjs:86:13)
    at _c1 (webpack-internal:///(app-pages-browser)/./components/ui/alert-dialog.tsx:44:11)
    at Provider (webpack-internal:///(app-pages-browser)/./node_modules/@radix-ui/react-dialog/node_modules/@radix-ui/react-context/dist/index.mjs:34:15)
    at Dialog (webpack-internal:///(app-pages-browser)/./node_modules/@radix-ui/react-dialog/dist/index.mjs:61:13)
    at AlertDialog (webpack-internal:///(app-pages-browser)/./node_modules/@radix-ui/react-alert-dialog/dist/index.mjs:47:13)
    at ErrorAlertDialog (webpack-internal:///(app-pages-browser)/./components/ui/error-alert-dialog.tsx:15:21)
    at div
    at PlaygroundPageContent (webpack-internal:///(app-pages-browser)/./pages/playground/playground-page.tsx:45:82)
    at PlaygroundPage
    at main
    at div
    at div
    at ViewComfyProvider (webpack-internal:///(app-pages-browser)/./app/providers/view-comfy-provider.tsx:126:11)
    at Page (webpack-internal:///(app-pages-browser)/./app/page.tsx:28:88)
    at ClientPageRoot (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/client-page.js:14:11)
    at InnerLayoutRouter (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/layout-router.js:243:11)
    at RedirectErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/redirect-boundary.js:74:9)
    at RedirectBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/redirect-boundary.js:82:11)
    at NotFoundErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/not-found-boundary.js:76:9)
    at NotFoundBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/not-found-boundary.js:84:11)
    at LoadingBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/layout-router.js:349:11)
    at ErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/error-boundary.js:160:11)
    at InnerScrollAndFocusHandler (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/layout-router.js:153:9)
    at ScrollAndFocusHandler (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/layout-router.js:228:11)
    at RenderFromTemplateContext (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/render-from-template-context.js:16:44)
    at OuterLayoutRouter (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/layout-router.js:370:11)
    at O (webpack-internal:///(app-pages-browser)/./node_modules/next-themes/dist/index.mjs:28:24)
    at z (webpack-internal:///(app-pages-browser)/./node_modules/next-themes/dist/index.mjs:21:47)
    at ThemeProvider (webpack-internal:///(app-pages-browser)/./components/theme-provider.tsx:13:11)
    at body
    at html
    at RootLayout (Server)
    at RedirectErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/redirect-boundary.js:74:9)
    at RedirectBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/redirect-boundary.js:82:11)
    at NotFoundErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/not-found-boundary.js:76:9)
    at NotFoundBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/not-found-boundary.js:84:11)
    at DevRootNotFoundBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/dev-root-not-found-boundary.js:33:11)
    at ReactDevOverlay (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/react-dev-overlay/app/ReactDevOverlay.js:87:9)
    at HotReload (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/react-dev-overlay/app/hot-reloader-client.js:321:11)
    at Router (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/app-router.js:207:11)
    at ErrorBoundaryHandler (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/error-boundary.js:113:9)
    at ErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/error-boundary.js:160:11)
    at AppRouter (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/app-router.js:585:13)
    at ServerRoot (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/app-index.js:112:27)
    at Root (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/app-index.js:117:11)

**Comment by chinchaun** [comment]
hey @laixiao, based on your logs I think you have an unsupported character in your inputs and comfyui server is failing because of that.

```
File "aiohttp\_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
Invalid method encountered:

b'\x16\x03\x01\x01j\x01'
  ^
```

**Comment by laixiao** [comment]
Is it compatible? Thank



------------------ Original ------------------
From: Jean Delannoy ***@***.***&gt;
Date: Fri,Dec 6,2024 11:45 PM
To: ViewComfy/ViewComfy ***@***.***&gt;
Cc: laixiao ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [ViewComfy/ViewComfy] Not working (Issue #55)





 
hey @laixiao, based on your logs I think you have an unsupported character in your inputs and comfyui server is failing because of that.
 File "aiohttp\_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data aiohttp.http_exceptions.BadStatusLine: 400, message: Invalid method encountered: b'\x16\x03\x01\x01j\x01'   ^

**Comment by chinchaun** [comment]
the issue coming from the server that runs comfyui, are you trying to run the same workflow with the same values in the comfyui interface?

**Comment by laixiao** [comment]
comfyui is ok





------------------ Original ------------------
From: Jean Delannoy ***@***.***&gt;
Date: Tue,Dec 10,2024 2:13 AM
To: ViewComfy/ViewComfy ***@***.***&gt;
Cc: laixiao ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [ViewComfy/ViewComfy] Not working (Issue #55)





 
the issue coming from the server that runs comfyui, are you trying to run the same workflow with the same values in the comfyui interface?

**Comment by chinchaun** [comment]
did you tried again with a different text input?

**Comment by chinchaun** [comment]
closing because the lack of activity
